# PV
kind: PersistentVolume
apiVersion: v1
metadata:
  name: php-server-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    # とりあえず100Miくらいの容量で試す
    storage: 100Mi
  # ホストないに作成したストレージへ、Kubernetes nodeがアクセスする際の制約事項
  # 今回は、単一のnodeのみに書き込み/読み込みを可能とする設定とした
  accessModes:
    - ReadWriteOnce
  hostPath:
    # ホストマシンのどこにストレージを割り当てるか
    path: '/root/src/lnmp/server'
---
# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-server-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
